// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:183430052939:web:2f4f3c5d364f818c5161ce',
    messagingSenderId: '183430052939',
    projectId: 'pariksha-cc65b',
    authDomain: 'pariksha-cc65b.firebaseapp.com',
    storageBucket: 'pariksha-cc65b.firebasestorage.app',
    measurementId: 'G-2C31CRRPXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN4jZppOm42HrOFkoaUI0Eb-',
    appId: '1:183430052939:android:3da6b1e9a8d4c16a5161ce',
    messagingSenderId: '183430052939',
    projectId: 'pariksha-cc65b',
    storageBucket: 'pariksha-cc65b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:183430052939:ios:5090d6c3a4ecb1605161ce',
    messagingSenderId: '183430052939',
    projectId: 'pariksha-cc65b',
    storageBucket: 'pariksha-cc65b.firebasestorage.app',
    iosBundleId: 'com.example.classcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:183430052939:ios:5090d6c3a4ecb1605161ce',
    messagingSenderId: '183430052939',
    projectId: 'pariksha-cc65b',
    storageBucket: 'pariksha-cc65b.firebasestorage.app',
    iosBundleId: 'com.example.classcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:183430052939:web:1bf6bd50881d075f5161ce',
    messagingSenderId: '183430052939',
    projectId: 'pariksha-cc65b',
    authDomain: 'pariksha-cc65b.firebaseapp.com',
    storageBucket: 'pariksha-cc65b.firebasestorage.app',
    measurementId: 'G-PEET2PRPK3',
  );

}
